/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package LaRussoSodoku;

/**
 *
 * @author Nikon
 */
public class mainPanel extends javax.swing.JPanel
{

    /**
     * Creates new form mainPanel
     */
    public mainPanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        text00 = new javax.swing.JTextField();
        text01 = new javax.swing.JTextField();
        text02 = new javax.swing.JTextField();
        text03 = new javax.swing.JTextField();
        text05 = new javax.swing.JTextField();
        text04 = new javax.swing.JTextField();
        text06 = new javax.swing.JTextField();
        text07 = new javax.swing.JTextField();
        text08 = new javax.swing.JTextField();
        text9 = new javax.swing.JTextField();
        text10 = new javax.swing.JTextField();
        text11 = new javax.swing.JTextField();
        text12 = new javax.swing.JTextField();
        text13 = new javax.swing.JTextField();
        text14 = new javax.swing.JTextField();
        text15 = new javax.swing.JTextField();
        text16 = new javax.swing.JTextField();
        text17 = new javax.swing.JTextField();
        text18 = new javax.swing.JTextField();
        text19 = new javax.swing.JTextField();
        text20 = new javax.swing.JTextField();
        text21 = new javax.swing.JTextField();
        text22 = new javax.swing.JTextField();
        text23 = new javax.swing.JTextField();
        text24 = new javax.swing.JTextField();
        text25 = new javax.swing.JTextField();
        text26 = new javax.swing.JTextField();
        text27 = new javax.swing.JTextField();
        text28 = new javax.swing.JTextField();
        text29 = new javax.swing.JTextField();
        text30 = new javax.swing.JTextField();
        text31 = new javax.swing.JTextField();
        text32 = new javax.swing.JTextField();
        text33 = new javax.swing.JTextField();
        text34 = new javax.swing.JTextField();
        text35 = new javax.swing.JTextField();
        text36 = new javax.swing.JTextField();
        text37 = new javax.swing.JTextField();
        text38 = new javax.swing.JTextField();
        text39 = new javax.swing.JTextField();
        text40 = new javax.swing.JTextField();
        text41 = new javax.swing.JTextField();
        text42 = new javax.swing.JTextField();
        text43 = new javax.swing.JTextField();
        text44 = new javax.swing.JTextField();
        text45 = new javax.swing.JTextField();
        text46 = new javax.swing.JTextField();
        text47 = new javax.swing.JTextField();
        text48 = new javax.swing.JTextField();
        text49 = new javax.swing.JTextField();
        text50 = new javax.swing.JTextField();
        text51 = new javax.swing.JTextField();
        text52 = new javax.swing.JTextField();
        text53 = new javax.swing.JTextField();
        text54 = new javax.swing.JTextField();
        text55 = new javax.swing.JTextField();
        text56 = new javax.swing.JTextField();
        text57 = new javax.swing.JTextField();
        text58 = new javax.swing.JTextField();
        text59 = new javax.swing.JTextField();
        text60 = new javax.swing.JTextField();
        text61 = new javax.swing.JTextField();
        text62 = new javax.swing.JTextField();
        text63 = new javax.swing.JTextField();
        text64 = new javax.swing.JTextField();
        text65 = new javax.swing.JTextField();
        text66 = new javax.swing.JTextField();
        text67 = new javax.swing.JTextField();
        text68 = new javax.swing.JTextField();
        text69 = new javax.swing.JTextField();
        text70 = new javax.swing.JTextField();
        text71 = new javax.swing.JTextField();
        text72 = new javax.swing.JTextField();
        text73 = new javax.swing.JTextField();
        text74 = new javax.swing.JTextField();
        text75 = new javax.swing.JTextField();
        text76 = new javax.swing.JTextField();
        text77 = new javax.swing.JTextField();
        text78 = new javax.swing.JTextField();
        text79 = new javax.swing.JTextField();
        text80 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        text00.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text00ActionPerformed(evt);
            }
        });

        text01.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text01ActionPerformed(evt);
            }
        });

        text02.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text02ActionPerformed(evt);
            }
        });

        text05.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text05ActionPerformed(evt);
            }
        });

        text04.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text04ActionPerformed(evt);
            }
        });

        text07.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text07ActionPerformed(evt);
            }
        });

        text08.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text08ActionPerformed(evt);
            }
        });

        text11.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text11ActionPerformed(evt);
            }
        });

        text12.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text12ActionPerformed(evt);
            }
        });

        text14.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text14ActionPerformed(evt);
            }
        });

        text15.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text15ActionPerformed(evt);
            }
        });

        text16.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text16ActionPerformed(evt);
            }
        });

        text17.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text17ActionPerformed(evt);
            }
        });

        text20.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text20ActionPerformed(evt);
            }
        });

        text21.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text21ActionPerformed(evt);
            }
        });

        text23.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text23ActionPerformed(evt);
            }
        });

        text24.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text24ActionPerformed(evt);
            }
        });

        text25.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text25ActionPerformed(evt);
            }
        });

        text26.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text26ActionPerformed(evt);
            }
        });

        text27.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text27ActionPerformed(evt);
            }
        });

        text29.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text29ActionPerformed(evt);
            }
        });

        text30.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text30ActionPerformed(evt);
            }
        });

        text33.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text33ActionPerformed(evt);
            }
        });

        text34.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text34ActionPerformed(evt);
            }
        });

        text36.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text36ActionPerformed(evt);
            }
        });

        text37.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text37ActionPerformed(evt);
            }
        });

        text38.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text38ActionPerformed(evt);
            }
        });

        text39.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text39ActionPerformed(evt);
            }
        });

        text40.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text40ActionPerformed(evt);
            }
        });

        text43.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text43ActionPerformed(evt);
            }
        });

        text44.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text44ActionPerformed(evt);
            }
        });

        text45.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text45ActionPerformed(evt);
            }
        });

        text46.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text46ActionPerformed(evt);
            }
        });

        text49.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text49ActionPerformed(evt);
            }
        });

        text50.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text50ActionPerformed(evt);
            }
        });

        text52.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text52ActionPerformed(evt);
            }
        });

        text53.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text53ActionPerformed(evt);
            }
        });

        text55.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text55ActionPerformed(evt);
            }
        });

        text56.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text56ActionPerformed(evt);
            }
        });

        text59.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text59ActionPerformed(evt);
            }
        });

        text60.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text60ActionPerformed(evt);
            }
        });

        text61.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text61ActionPerformed(evt);
            }
        });

        text62.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text62ActionPerformed(evt);
            }
        });

        text64.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text64ActionPerformed(evt);
            }
        });

        text67.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text67ActionPerformed(evt);
            }
        });

        text69.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text69ActionPerformed(evt);
            }
        });

        text70.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text70ActionPerformed(evt);
            }
        });

        text71.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text71ActionPerformed(evt);
            }
        });

        text73.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text73ActionPerformed(evt);
            }
        });

        text75.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text75ActionPerformed(evt);
            }
        });

        text76.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text76ActionPerformed(evt);
            }
        });

        text77.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text77ActionPerformed(evt);
            }
        });

        text78.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text78ActionPerformed(evt);
            }
        });

        text79.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text79ActionPerformed(evt);
            }
        });

        text80.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                text80ActionPerformed(evt);
            }
        });

        jButton1.setText("solve");

        jButton2.setText("clear");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text00, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text01, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text02, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(text03, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text04, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text05, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(text06, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text07, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text08, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text17, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(text10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(text13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text25, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text26, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text18, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(text19, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text21, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text20, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(text22, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text23, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text24, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text39, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text40, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text41, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(text42, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text27, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text43, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(text28, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text29, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text30, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text45, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text46, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text31, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(text32, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text34, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text33, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(text35, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text36, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text44, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text37, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text38, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text47, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(text48, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text50, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text49, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(text51, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text52, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text53, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text67, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text56, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text57, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(text74, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text59, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text77, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(text54, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text79, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text70, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text75, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text55, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text68, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(text65, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text76, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text78, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(text66, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text60, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text61, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text69, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text80, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text58, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(text63, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text64, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text73, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(text72, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text62, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text71, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text00, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text01, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text02, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text05, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text04, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text07, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text08, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text06, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text03, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text16, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text17, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text25, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text26, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text18, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text20, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text21, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text23, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text24, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text22, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text19, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text39, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text40, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text41, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text43, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text27, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text29, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text30, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text28, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text42, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text45, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text46, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text31, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text33, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text34, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text36, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text44, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text35, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text32, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text37, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text38, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text47, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text49, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text50, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text52, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text53, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text51, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text48, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text75, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text55, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text68, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text78, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text76, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text60, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text61, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text66, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text65, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text67, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text56, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text57, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text77, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text59, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text79, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text70, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text54, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text74, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text69, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text80, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text58, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text73, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text64, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text62, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text71, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text72, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text63, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void text00ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text00ActionPerformed
    {//GEN-HEADEREND:event_text00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text00ActionPerformed

    private void text01ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text01ActionPerformed
    {//GEN-HEADEREND:event_text01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text01ActionPerformed

    private void text05ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text05ActionPerformed
    {//GEN-HEADEREND:event_text05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text05ActionPerformed

    private void text04ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text04ActionPerformed
    {//GEN-HEADEREND:event_text04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text04ActionPerformed

    private void text07ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text07ActionPerformed
    {//GEN-HEADEREND:event_text07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text07ActionPerformed

    private void text08ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text08ActionPerformed
    {//GEN-HEADEREND:event_text08ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text08ActionPerformed

    private void text11ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text11ActionPerformed
    {//GEN-HEADEREND:event_text11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text11ActionPerformed

    private void text12ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text12ActionPerformed
    {//GEN-HEADEREND:event_text12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text12ActionPerformed

    private void text14ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text14ActionPerformed
    {//GEN-HEADEREND:event_text14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text14ActionPerformed

    private void text15ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text15ActionPerformed
    {//GEN-HEADEREND:event_text15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text15ActionPerformed

    private void text16ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text16ActionPerformed
    {//GEN-HEADEREND:event_text16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text16ActionPerformed

    private void text17ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text17ActionPerformed
    {//GEN-HEADEREND:event_text17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text17ActionPerformed

    private void text20ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text20ActionPerformed
    {//GEN-HEADEREND:event_text20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text20ActionPerformed

    private void text21ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text21ActionPerformed
    {//GEN-HEADEREND:event_text21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text21ActionPerformed

    private void text23ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text23ActionPerformed
    {//GEN-HEADEREND:event_text23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text23ActionPerformed

    private void text24ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text24ActionPerformed
    {//GEN-HEADEREND:event_text24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text24ActionPerformed

    private void text25ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text25ActionPerformed
    {//GEN-HEADEREND:event_text25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text25ActionPerformed

    private void text26ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text26ActionPerformed
    {//GEN-HEADEREND:event_text26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text26ActionPerformed

    private void text27ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text27ActionPerformed
    {//GEN-HEADEREND:event_text27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text27ActionPerformed

    private void text29ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text29ActionPerformed
    {//GEN-HEADEREND:event_text29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text29ActionPerformed

    private void text30ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text30ActionPerformed
    {//GEN-HEADEREND:event_text30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text30ActionPerformed

    private void text33ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text33ActionPerformed
    {//GEN-HEADEREND:event_text33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text33ActionPerformed

    private void text34ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text34ActionPerformed
    {//GEN-HEADEREND:event_text34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text34ActionPerformed

    private void text36ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text36ActionPerformed
    {//GEN-HEADEREND:event_text36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text36ActionPerformed

    private void text37ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text37ActionPerformed
    {//GEN-HEADEREND:event_text37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text37ActionPerformed

    private void text38ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text38ActionPerformed
    {//GEN-HEADEREND:event_text38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text38ActionPerformed

    private void text39ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text39ActionPerformed
    {//GEN-HEADEREND:event_text39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text39ActionPerformed

    private void text40ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text40ActionPerformed
    {//GEN-HEADEREND:event_text40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text40ActionPerformed

    private void text43ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text43ActionPerformed
    {//GEN-HEADEREND:event_text43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text43ActionPerformed

    private void text44ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text44ActionPerformed
    {//GEN-HEADEREND:event_text44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text44ActionPerformed

    private void text45ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text45ActionPerformed
    {//GEN-HEADEREND:event_text45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text45ActionPerformed

    private void text46ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text46ActionPerformed
    {//GEN-HEADEREND:event_text46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text46ActionPerformed

    private void text49ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text49ActionPerformed
    {//GEN-HEADEREND:event_text49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text49ActionPerformed

    private void text50ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text50ActionPerformed
    {//GEN-HEADEREND:event_text50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text50ActionPerformed

    private void text52ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text52ActionPerformed
    {//GEN-HEADEREND:event_text52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text52ActionPerformed

    private void text53ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text53ActionPerformed
    {//GEN-HEADEREND:event_text53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text53ActionPerformed

    private void text55ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text55ActionPerformed
    {//GEN-HEADEREND:event_text55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text55ActionPerformed

    private void text56ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text56ActionPerformed
    {//GEN-HEADEREND:event_text56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text56ActionPerformed

    private void text59ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text59ActionPerformed
    {//GEN-HEADEREND:event_text59ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text59ActionPerformed

    private void text60ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text60ActionPerformed
    {//GEN-HEADEREND:event_text60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text60ActionPerformed

    private void text61ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text61ActionPerformed
    {//GEN-HEADEREND:event_text61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text61ActionPerformed

    private void text62ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text62ActionPerformed
    {//GEN-HEADEREND:event_text62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text62ActionPerformed

    private void text64ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text64ActionPerformed
    {//GEN-HEADEREND:event_text64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text64ActionPerformed

    private void text67ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text67ActionPerformed
    {//GEN-HEADEREND:event_text67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text67ActionPerformed

    private void text69ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text69ActionPerformed
    {//GEN-HEADEREND:event_text69ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text69ActionPerformed

    private void text70ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text70ActionPerformed
    {//GEN-HEADEREND:event_text70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text70ActionPerformed

    private void text71ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text71ActionPerformed
    {//GEN-HEADEREND:event_text71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text71ActionPerformed

    private void text73ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text73ActionPerformed
    {//GEN-HEADEREND:event_text73ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text73ActionPerformed

    private void text75ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text75ActionPerformed
    {//GEN-HEADEREND:event_text75ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text75ActionPerformed

    private void text76ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text76ActionPerformed
    {//GEN-HEADEREND:event_text76ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text76ActionPerformed

    private void text77ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text77ActionPerformed
    {//GEN-HEADEREND:event_text77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text77ActionPerformed

    private void text78ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text78ActionPerformed
    {//GEN-HEADEREND:event_text78ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text78ActionPerformed

    private void text79ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text79ActionPerformed
    {//GEN-HEADEREND:event_text79ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text79ActionPerformed

    private void text80ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text80ActionPerformed
    {//GEN-HEADEREND:event_text80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text80ActionPerformed

    private void text02ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_text02ActionPerformed
    {//GEN-HEADEREND:event_text02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text02ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField text00;
    private javax.swing.JTextField text01;
    private javax.swing.JTextField text02;
    private javax.swing.JTextField text03;
    private javax.swing.JTextField text04;
    private javax.swing.JTextField text05;
    private javax.swing.JTextField text06;
    private javax.swing.JTextField text07;
    private javax.swing.JTextField text08;
    private javax.swing.JTextField text10;
    private javax.swing.JTextField text11;
    private javax.swing.JTextField text12;
    private javax.swing.JTextField text13;
    private javax.swing.JTextField text14;
    private javax.swing.JTextField text15;
    private javax.swing.JTextField text16;
    private javax.swing.JTextField text17;
    private javax.swing.JTextField text18;
    private javax.swing.JTextField text19;
    private javax.swing.JTextField text20;
    private javax.swing.JTextField text21;
    private javax.swing.JTextField text22;
    private javax.swing.JTextField text23;
    private javax.swing.JTextField text24;
    private javax.swing.JTextField text25;
    private javax.swing.JTextField text26;
    private javax.swing.JTextField text27;
    private javax.swing.JTextField text28;
    private javax.swing.JTextField text29;
    private javax.swing.JTextField text30;
    private javax.swing.JTextField text31;
    private javax.swing.JTextField text32;
    private javax.swing.JTextField text33;
    private javax.swing.JTextField text34;
    private javax.swing.JTextField text35;
    private javax.swing.JTextField text36;
    private javax.swing.JTextField text37;
    private javax.swing.JTextField text38;
    private javax.swing.JTextField text39;
    private javax.swing.JTextField text40;
    private javax.swing.JTextField text41;
    private javax.swing.JTextField text42;
    private javax.swing.JTextField text43;
    private javax.swing.JTextField text44;
    private javax.swing.JTextField text45;
    private javax.swing.JTextField text46;
    private javax.swing.JTextField text47;
    private javax.swing.JTextField text48;
    private javax.swing.JTextField text49;
    private javax.swing.JTextField text50;
    private javax.swing.JTextField text51;
    private javax.swing.JTextField text52;
    private javax.swing.JTextField text53;
    private javax.swing.JTextField text54;
    private javax.swing.JTextField text55;
    private javax.swing.JTextField text56;
    private javax.swing.JTextField text57;
    private javax.swing.JTextField text58;
    private javax.swing.JTextField text59;
    private javax.swing.JTextField text60;
    private javax.swing.JTextField text61;
    private javax.swing.JTextField text62;
    private javax.swing.JTextField text63;
    private javax.swing.JTextField text64;
    private javax.swing.JTextField text65;
    private javax.swing.JTextField text66;
    private javax.swing.JTextField text67;
    private javax.swing.JTextField text68;
    private javax.swing.JTextField text69;
    private javax.swing.JTextField text70;
    private javax.swing.JTextField text71;
    private javax.swing.JTextField text72;
    private javax.swing.JTextField text73;
    private javax.swing.JTextField text74;
    private javax.swing.JTextField text75;
    private javax.swing.JTextField text76;
    private javax.swing.JTextField text77;
    private javax.swing.JTextField text78;
    private javax.swing.JTextField text79;
    private javax.swing.JTextField text80;
    private javax.swing.JTextField text9;
    // End of variables declaration//GEN-END:variables
}
